import type { Booking, EventItem } from "@/lib/organizer"

export const mockEvents: EventItem[] = [
  {
    id: "evt_rock101",
    title: "Rock Night 101",
    category: "Music",
    startAt: new Date().toISOString(),
    endAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    location: "Bengaluru, KA",
    visibility: "public",
    posterUrl: "/rock-concert-21-9.png",
    logoUrl: undefined,
    tickets: [
      { id: "t1", name: "Basic", price: 799, quantity: 300, sold: 220 },
      { id: "t2", name: "VIP", price: 1599, quantity: 50, sold: 45 },
    ],
    status: "published",
    revenue: 799 * 220 + 1599 * 45,
    ticketsLeft: 300 + 50 - (220 + 45),
    sold: 220 + 45,
  },
  {
    id: "evt_artfest",
    title: "Indie Art Festival",
    category: "Art",
    startAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endAt: new Date(Date.now() + 27 * 60 * 60 * 1000).toISOString(),
    location: "Mumbai, MH",
    visibility: "private",
    posterUrl: "/art-festival-21-9.png",
    logoUrl: undefined,
    tickets: [
      { id: "t1", name: "General", price: 499, quantity: 500, sold: 120 },
      { id: "t2", name: "VIP", price: 1499, quantity: 40, sold: 12 },
    ],
    status: "draft",
    revenue: 499 * 120 + 1499 * 12,
    ticketsLeft: 500 + 40 - (120 + 12),
    sold: 120 + 12,
  },
]

export const mockBookings: Booking[] = [
  {
    id: "ord_001",
    eventId: "evt_rock101",
    buyerName: "Amit Verma",
    buyerEmail: "amit@example.com",
    buyerPhone: "9876543210",
    qty: 3,
    amount: 799 * 2 + 1599 * 1,
    paymentStatus: "paid",
    checkinStatus: "not_checked_in",
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ord_002",
    eventId: "evt_rock101",
    buyerName: "Priya Sharma",
    buyerEmail: "priya@example.com",
    buyerPhone: "9876500001",
    qty: 2,
    amount: 1599 * 2,
    paymentStatus: "paid",
    checkinStatus: "checked_in",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ord_003",
    eventId: "evt_artfest",
    buyerName: "Rahul Mehta",
    buyerEmail: "rahul@example.com",
    buyerPhone: "9999999999",
    qty: 1,
    amount: 499,
    paymentStatus: "pending",
    checkinStatus: "not_checked_in",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockFeedback = [
  {
    id: "fb_1",
    eventId: "evt_rock101",
    rating: 5,
    comment: "Amazing sound and great vibe!",
    reviewer: "Sanjana",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fb_2",
    eventId: "evt_rock101",
    rating: 4,
    comment: "Loved the setlist, seating could be better.",
    reviewer: "Ravi",
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fb_3",
    eventId: "evt_artfest",
    rating: 3,
    comment: "Good curation, but too crowded.",
    reviewer: "Neha",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
]
