import type { Event } from "@/components/event-card"

export const events: Event[] = [
  {
    id: "ev-aurora-fest",
    poster: "/image.png",
    logo: "/image.png",
    title: "Aurora Night Music Fest",
    description:
      "Immerse yourself in an electrifying night of music, lights, and immersive installations featuring world-class DJs and visual artists.",
    category: "Music",
    date: "Oct 12, 2025",
    time: "7:00 PM",
    location: "CGC Jhenjeri, Chandigarh",
    status: "ongoing",
    tickets: [
      { tier: "Basic", price: 39, stock: 80 },
      { tier: "Standard", price: 69, stock: 120 },
      { tier: "VIP", price: 149, stock: 25 },
    ],
  },
  {
    id: "ev-aurora",
    poster: "/image.png",
    logo: "/image.png",
    title: "Bollywood Night Concert",
    description:
      "A spectacular evening of Bollywood hits featuring live performances by top playback singers and dancers.",
    category: "Concert",
    date: "Oct 15, 2025",
    time: "8:00 PM",
    location: "Panipat Institute of Engineering and Technology",
    status: "ongoing",
    tickets: [
      { tier: "Basic", price: 45, stock: 150 },
      { tier: "Standard", price: 85, stock: 100 },
      { tier: "VIP", price: 199, stock: 30 },
    ],
  },
  {
    id: "ev-ngo-blood-drive",
    poster: "/blood.jpg",
    logo: "/blood.jpg",
    title: "Blood Donation Drive - Save Lives",
    description:
      "Join hands with Red Cross Society for a noble cause. Every drop counts! Free health checkup, certificates, and refreshments provided.",
    category: "NGO & Social",
    date: "Aug 30, 2025",
    time: "9:00 AM",
    location: "Community Health Center, Sector 34, Chandigarh",
    status: "ongoing",
    tickets: [
      { tier: "Volunteer", price: 0, stock: 200 },
      { tier: "Donor", price: 0, stock: 500 },
      { tier: "Supporter", price: 50, stock: 100 },
    ],
  },
  {
    id: "ev-gaming-zone-tournament",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Gaming Zone Championship 2025",
    description:
      "Ultimate gaming experience with PS5, Xbox, VR gaming, and retro arcade games. Tournaments running all day with exciting prizes!",
    category: "Gaming",
    date: "Aug 30, 2025",
    time: "10:00 AM",
    location: "GameZone Arena, Phoenix Mall, Mohali",
    status: "ongoing",
    tickets: [
      { tier: "Gaming Pass", price: 150, stock: 300 },
      { tier: "Tournament Entry", price: 250, stock: 100 },
      { tier: "VIP Gaming", price: 500, stock: 50 },
    ],
  },
  {
    id: "ev-corporate-infosys",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Infosys Innovation Summit",
    description:
      "Corporate networking event featuring AI innovations, career opportunities, tech demos, and interactive workshops with industry leaders.",
    category: "Corporate",
    date: "Aug 30, 2025",
    time: "11:00 AM",
    location: "Infosys Campus, Electronic City, Bangalore",
    status: "ongoing",
    tickets: [
      { tier: "Student", price: 0, stock: 1000 },
      { tier: "Professional", price: 200, stock: 500 },
      { tier: "Executive", price: 500, stock: 100 },
    ],
  },
  {
    id: "ev-travel-himachal",
    poster: "/travel.avif",
    logo: "/travel.avif",
    title: "Himalayan Adventure Trek",
    description:
      "5-day guided trekking expedition to Triund and McLeod Ganj. Includes accommodation, meals, professional guides, and safety equipment.",
    category: "Travel & Adventure",
    date: "Aug 30, 2025",
    time: "6:00 AM",
    location: "Departure: Chandigarh Bus Stand",
    status: "ongoing",
    tickets: [
      { tier: "Budget Trek", price: 3500, stock: 40 },
      { tier: "Comfort Trek", price: 5500, stock: 25 },
      { tier: "Premium Trek", price: 8500, stock: 15 },
    ],
  },
  {
    id: "ev-ngo-beach-cleanup",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Coastal Cleanup Drive",
    description:
      "Join Ocean Warriors NGO for a beach cleanup initiative. Make our coasts plastic-free! Tools provided, lunch included.",
    category: "NGO & Social",
    date: "Aug 30, 2025",
    time: "7:00 AM",
    location: "Juhu Beach, Mumbai",
    status: "ongoing",
    tickets: [
      { tier: "Volunteer", price: 0, stock: 300 },
      { tier: "Team Leader", price: 0, stock: 50 },
      { tier: "Donor", price: 100, stock: 200 },
    ],
  },
  {
    id: "ev-vr-gaming-expo",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Virtual Reality Gaming Expo",
    description:
      "Experience the future of gaming with cutting-edge VR technology, AR experiences, and immersive simulations from top gaming companies.",
    category: "Gaming",
    date: "Aug 30, 2025",
    time: "12:00 PM",
    location: "Cyber Hub, Gurgaon",
    status: "ongoing",
    tickets: [
      { tier: "Basic Access", price: 200, stock: 400 },
      { tier: "Premium Experience", price: 400, stock: 200 },
      { tier: "Developer Pass", price: 800, stock: 100 },
    ],
  },
  {
    id: "ev-corporate-tcs-hiring",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "TCS Campus Recruitment Drive",
    description:
      "Exclusive hiring event for fresh graduates and experienced professionals. Technical interviews, HR rounds, and instant offer letters.",
    category: "Corporate",
    date: "Aug 30, 2025",
    time: "9:30 AM",
    location: "TCS Campus, Pune",
    status: "ongoing",
    tickets: [
      { tier: "Fresher", price: 0, stock: 800 },
      { tier: "Experienced", price: 0, stock: 200 },
      { tier: "Premium Profile", price: 100, stock: 50 },
    ],
  },
  {
    id: "ev-travel-goa-festival",
    poster: "/travel.avif",
    logo: "/travel.avif",
    title: "Goa Beach Music Festival",
    description:
      "3-day beach festival with international DJs, water sports, beach camping, and Goan cuisine. Transportation and accommodation included.",
    category: "Travel & Adventure",
    date: "Aug 30, 2025",
    time: "4:00 PM",
    location: "Anjuna Beach, Goa",
    status: "ongoing",
    tickets: [
      { tier: "Backpacker", price: 4500, stock: 200 },
      { tier: "Beach Villa", price: 8500, stock: 100 },
      { tier: "Luxury Resort", price: 15000, stock: 50 },
    ],
  },
  {
    id: "ev-ngo-education-drive",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Digital Education for All",
    description:
      "Help distribute tablets and conduct digital literacy workshops for underprivileged children. Teaching volunteers needed!",
    category: "NGO & Social",
    date: "Aug 30, 2025",
    time: "10:00 AM",
    location: "Government School, Dwarka, Delhi",
    status: "ongoing",
    tickets: [
      { tier: "Volunteer Teacher", price: 0, stock: 100 },
      { tier: "Material Donor", price: 500, stock: 200 },
      { tier: "Sponsor", price: 2000, stock: 50 },
    ],
  },
  {
    id: "ev-tech-fest",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "TechnoVision 2025",
    description:
      "The biggest college tech fest featuring coding competitions, robotics, hackathons, and tech exhibitions.",
    category: "College Fest",
    date: "Oct 18, 2025",
    time: "9:00 AM",
    location: "Chandigarh University",
    status: "upcoming",
    tickets: [
      { tier: "Student", price: 15, stock: 500 },
      { tier: "General", price: 25, stock: 300 },
      { tier: "Premium", price: 50, stock: 100 },
    ],
  },
  {
    id: "ev-cultural-fest",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Rang-De-Basanti Cultural Fest",
    description:
      "A vibrant celebration of Indian culture with dance competitions, drama, music, and traditional food stalls.",
    category: "College Fest",
    date: "Nov 2, 2025",
    time: "10:00 AM",
    location: "Delhi University, North Campus",
    status: "upcoming",
    tickets: [
      { tier: "Student", price: 10, stock: 800 },
      { tier: "General", price: 20, stock: 400 },
      { tier: "VIP", price: 75, stock: 50 },
    ],
  },
  {
    id: "ev-rock-concert",
    poster: "/image.png",
    logo: "/image.png",
    title: "Rock Legends Live",
    description:
      "An epic rock concert featuring legendary bands and upcoming rock artists. Pure energy and headbanging music!",
    category: "Concert",
    date: "Oct 25, 2025",
    time: "7:30 PM",
    location: "Pragati Maidan, New Delhi",
    status: "upcoming",
    tickets: [
      { tier: "General", price: 60, stock: 1000 },
      { tier: "Premium", price: 120, stock: 500 },
      { tier: "VIP", price: 250, stock: 100 },
    ],
  },
  {
    id: "ev-classical-evening",
    poster: "/image.png",
    logo: "/image.png",
    title: "Classical Music Evening",
    description:
      "An enchanting evening of classical Indian music featuring renowned sitar, tabla, and vocal artists.",
    category: "Music",
    date: "Nov 8, 2025",
    time: "6:00 PM",
    location: "India Habitat Centre, Delhi",
    status: "upcoming",
    tickets: [
      { tier: "Standard", price: 80, stock: 200 },
      { tier: "Premium", price: 150, stock: 100 },
      { tier: "Royal", price: 300, stock: 25 },
    ],
  },
  {
    id: "ev-startup-summit",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Startup India Summit",
    description:
      "Connect with entrepreneurs, investors, and industry leaders. Pitch sessions, workshops, and networking opportunities.",
    category: "Conference",
    date: "Nov 12, 2025",
    time: "9:30 AM",
    location: "Hyderabad International Convention Centre",
    status: "upcoming",
    tickets: [
      { tier: "Student", price: 50, stock: 300 },
      { tier: "Professional", price: 150, stock: 400 },
      { tier: "VIP", price: 500, stock: 50 },
    ],
  },
  {
    id: "ev-comedy-night",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Stand-Up Comedy Night",
    description:
      "Laugh out loud with India's top stand-up comedians. An evening filled with humor, wit, and entertainment.",
    category: "Entertainment",
    date: "Oct 20, 2025",
    time: "8:30 PM",
    location: "Phoenix MarketCity, Pune",
    status: "upcoming",
    tickets: [
      { tier: "Regular", price: 40, stock: 250 },
      { tier: "Premium", price: 70, stock: 100 },
      { tier: "VIP", price: 120, stock: 30 },
    ],
  },
  {
    id: "ev-food-festival",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Street Food Carnival",
    description:
      "A gastronomic journey through India's best street food. Over 100 food stalls, live cooking shows, and competitions.",
    category: "Food & Drink",
    date: "Oct 28, 2025",
    time: "5:00 PM",
    location: "Nehru Park, Chanakyapuri, Delhi",
    status: "upcoming",
    tickets: [
      { tier: "Entry", price: 25, stock: 2000 },
      { tier: "Food Pass", price: 75, stock: 800 },
      { tier: "VIP Experience", price: 150, stock: 100 },
    ],
  },
  {
    id: "ev-sports-meet",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Inter-College Sports Championship",
    description:
      "Annual sports championship featuring cricket, football, basketball, athletics, and more. Compete for glory!",
    category: "Sports",
    date: "Nov 15, 2025",
    time: "8:00 AM",
    location: "Jawaharlal Nehru Stadium, Delhi",
    status: "upcoming",
    tickets: [
      { tier: "Participant", price: 30, stock: 1000 },
      { tier: "Spectator", price: 15, stock: 3000 },
      { tier: "Premium", price: 50, stock: 200 },
    ],
  },
  {
    id: "ev-art-exhibition",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Contemporary Art Showcase",
    description:
      "Explore modern Indian art with works from emerging and established artists. Interactive installations and live painting.",
    category: "Arts & Culture",
    date: "Nov 5, 2025",
    time: "11:00 AM",
    location: "National Gallery of Modern Art, Mumbai",
    status: "upcoming",
    tickets: [
      { tier: "Regular", price: 35, stock: 400 },
      { tier: "Art Lover", price: 65, stock: 200 },
      { tier: "Collector", price: 150, stock: 50 },
    ],
  },
  {
    id: "ev-gaming-tournament",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "eSports Gaming Championship",
    description:
      "The ultimate gaming tournament featuring PUBG, Valorant, FIFA, and more. Massive prize pools and live streaming!",
    category: "Gaming",
    date: "Oct 30, 2025",
    time: "10:00 AM",
    location: "Bangalore International Exhibition Centre",
    status: "upcoming",
    tickets: [
      { tier: "Participant", price: 20, stock: 500 },
      { tier: "Spectator", price: 10, stock: 1000 },
      { tier: "VIP", price: 80, stock: 100 },
    ],
  },
  {
    id: "ev-dance-battle",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "National Dance Battle",
    description:
      "The biggest dance competition featuring hip-hop, contemporary, classical, and fusion dance styles from across India.",
    category: "Dance",
    date: "Nov 10, 2025",
    time: "6:00 PM",
    location: "Siri Fort Auditorium, Delhi",
    status: "upcoming",
    tickets: [
      { tier: "Regular", price: 30, stock: 800 },
      { tier: "Premium", price: 60, stock: 300 },
      { tier: "VIP", price: 100, stock: 50 },
    ],
  },
  {
    id: "ev-book-fair",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "Literary Festival & Book Fair",
    description:
      "Meet your favorite authors, attend book readings, poetry sessions, and discover new literary works from publishers.",
    category: "Literature",
    date: "Nov 20, 2025",
    time: "10:00 AM",
    location: "Pragati Maidan, New Delhi",
    status: "upcoming",
    tickets: [
      { tier: "Basic", price: 20, stock: 1500 },
      { tier: "Bookworm", price: 40, stock: 500 },
      { tier: "Author Meet", price: 100, stock: 100 },
    ],
  },
  {
    id: "ev-dev-summit",
    poster: "/developer-summit-poster.png",
    logo: "/dev-summit-logo.png",
    title: "Global Developer Summit",
    description:
      "A two-day conference for modern web and AI developers. Talks, workshops, and hands-on labs from industry leaders.",
    category: "Conference",
    date: "Nov 4–5, 2025",
    time: "9:00 AM",
    location: "Moscone West, San Francisco",
    status: "upcoming",
    tickets: [
      { tier: "Basic", price: 99, stock: 200 },
      { tier: "Standard", price: 179, stock: 180 },
      { tier: "VIP", price: 399, stock: 40 },
    ],
  },
  {
    id: "ev-design-days",
    poster: "/design-days-poster.png",
    logo: "/design-days-logo.png",
    title: "Design Days Expo",
    description:
      "Explore the future of product design with live demos, portfolio reviews, and interactive exhibits from top studios.",
    category: "Arts & Culture",
    date: "Aug 04, 2025",
    time: "10:00 AM",
    location: "Expo Center, Berlin",
    status: "past",
    tickets: [
      { tier: "Basic", price: 25, stock: 0 },
      { tier: "Standard", price: 49, stock: 0 },
      { tier: "VIP", price: 119, stock: 0 },
    ],
  },
  {
    id: "ev-fashion-week",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "India Fashion Week",
    description:
      "Witness the latest fashion trends from top designers. Runway shows, designer exhibitions, and style workshops.",
    category: "Fashion",
    date: "Aug 15, 2025",
    time: "7:00 PM",
    location: "NSIC Exhibition Complex, Delhi",
    status: "past",
    tickets: [
      { tier: "General", price: 80, stock: 0 },
      { tier: "Fashion Pass", price: 150, stock: 0 },
      { tier: "VIP", price: 300, stock: 0 },
    ],
  },
  {
    id: "ev-hackathon",
    poster: "/aurora-night-festival-poster.png",
    logo: "/aurora-logo.png",
    title: "48-Hour Coding Hackathon",
    description:
      "Build innovative solutions in 48 hours! AI, blockchain, web development challenges with mentorship and prizes.",
    category: "Technology",
    date: "Sep 10, 2025",
    time: "9:00 AM",
    location: "IIT Delhi",
    status: "past",
    tickets: [
      { tier: "Individual", price: 25, stock: 0 },
      { tier: "Team", price: 80, stock: 0 },
      { tier: "Premium", price: 150, stock: 0 },
    ],
  },
]
